FROM node:20-alpine AS builder
WORKDIR /app
ARG VITE_GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM scratch AS export
COPY --from=builder /app/dist /app/dist
