import os

BEGINNER_DISTRIBUTION = {"easy": 70, "medium": 25, "hard": 5}
INTERMEDIATE_DISTRIBUTION = {"easy": 30, "medium": 50, "hard": 20}
ADVANCED_DISTRIBUTION = {"easy": 10, "medium": 40, "hard": 50}

ADVANCED_HARD_ATTEMPT_THRESHOLD = 3
ADVANCED_HARD_SCORE_THRESHOLD = 0.6
INTERMEDIATE_MEDIUM_SCORE_THRESHOLD = 0.6

DEFAULT_TOTAL_QUESTIONS = 20
DEFAULT_BACKEND_BASE_URL = os.environ.get(
    "VEGA_BACKEND_BASE_URL", "http://localhost:81"
)
DEFAULT_USER_ID = os.environ.get("VEGA_USER_ID")
DEFAULT_AUTH_TOKEN = os.environ.get("VEGA_AUTH_TOKEN")
DEFAULT_AUTH_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3ODk2OTcxMSwianRpIjoiYTQ2YTRlYTMtNDdjMS00Njc1LTk5ZTItODRkNzc4ZGQxYzNhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjVkYjc3YWU1LTRiZDQtNDY1ZS05NjQxLTRiYThjNTExZjg0NiIsIm5iZiI6MTc3ODk2OTcxMSwiY3NyZiI6IjExNTAwNjc1LWFmYzktNDBhMi1hMWE2LWU5MWEwOGQ1M2ZhNSIsImV4cCI6MTc3OTA1NjExMX0.gPqYhzsojIzbMLNainV42V9yoZssF-31hCLExyKgN38"
